module SBOM
  module CycloneDX
    module Validator
      class ArrayValidator < BaseValidator[::Array[fieldValue]]
        type itemsValidator = ^(untyped) -> Array[String]
        type validSingleTypeLabel =
          :boolean
        | :date_time
        | :email_address
        | :float
        | :integer
        | singleton(SBOM::CycloneDX::Record::Base)
        | :string
        | :uri

        @items_validator: BaseValidator[fieldValue]
        @unique: bool

        def initialize: (
            items: itemsValidator | validSingleTypeLabel | Validator::arrayItemValidatorParams,
            ?unique: bool,
            ?required: bool
          ) -> void

        def valid?: (untyped) -> bool
        private def validator_method: (SBOM::CycloneDX::Validator::BaseValidator[untyped]) -> ^(untyped) -> Array[String]
        private def proc_validator: (^(untyped) -> (bool | Array[untyped] | String)) -> ^(untyped) -> Array[String]
      end
    end
  end
end
