module SBOM
  module CycloneDX
    module Validator
      class BaseValidator[in T < fieldValue]
        MISSING_REQUIRED: String
        INVALID_TYPE: String

        @types: Array[fieldType]
        @required: bool
        @errors: Array[String]

        def initialize: (*fieldType, ?required: bool) -> void
        def valid?: (untyped) -> bool
        def validate: (untyped) -> Array[String]
        def required?: () -> bool
        def const?: () -> bool
        def raw_types: () -> Array[fieldType]
      end
    end
  end
end
