module SBOM
  module CycloneDX
    module Validator
      class DateTimeValidator < BaseValidator[dateTime]
        def initialize: (?required: bool) -> void
        def valid?: (untyped) -> bool
      end
    end
  end
end
