module SBOM
  module CycloneDX
    module Validator
      class FloatValidator < BaseValidator[Float]
        @range: Range[number?]

        def initialize: (?maximum: number?, ?minimum: number?, ?required: bool) -> void
        def valid?: (untyped) -> bool
      end
    end
  end
end
