module SBOM
  module CycloneDX
    module Validator
      class RecordValidator < BaseValidator[Record::Base]
        @record_type: singleton(SBOM::CycloneDX::Record::Base)

        def initialize: (type: singleton(SBOM::CycloneDX::Record::Base), ?required: bool) -> void
        def valid?: (untyped) -> bool
      end
    end
  end
end
