module SBOM
  module CycloneDX
    module Validator
      class StringValidator < BaseValidator[String]
        @enum: Array[String]?
        @length_range: Range[Integer?]
        @pattern: Regexp

        def initialize: (?enum: Array[String]?, ?max_length: Integer?, ?min_length: Integer?, ?pattern: Regexp, ?required: bool, **untyped) -> void
        def valid?: (untyped) -> bool
      end
    end
  end
end
