module SBOM
  module CycloneDX
    module Type
      module Boolean
      end

      class Union
        @types: Array[fieldTypeLabel]

        def self.[]: [T < fieldTypeLabel] (*T) -> instance

        private def initialize: [T < fieldTypeLabel] (*T) -> void
      end
    end
  end
end
