default:
  tags:
    - runner-small
  image: ruby:3.3.4
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install rbs steep
    - rbs collection install
    - gem install bundler -v 2.5.17
    - bundle config set --local deployment
    - bundle install -j $(nproc)
steep:
  stage: test
  script:
    - steep check
rubocop:
  stage: test
  script:
    - rubocop
rspec:
  stage: test
  variables:
    RBS_TEST_TARGET: "SBOM::CycloneDX::*"
    RUBYOPT: "-rrbs/test/setup"
  script:
    - rspec spec
