.ruby-base:
  tags:
    - runner-small
  image: $RUBY_IMAGE
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - ./vendor/ruby
      - ./.gem_rbs_collection
  before_script:
    - ruby -v
    - apk update && apk --no-cache add --virtual bash git curl curl-dev ruby-dev build-base ruby ruby-io-console ruby-irb ruby-json ruby-etc ruby-bigdecimal ruby-rdoc libffi-dev zlib-dev yaml-dev
    - bundle config set path ./vendor/ruby
    - bundle install --jobs=$(nproc) --retry=3
    - bundle exec rbs collection install --frozen
  variables:
    RUBY_IMAGE: ruby:3.3-alpine
lint:
  extends: .ruby-base
  stage: test
  script:
    - bundle exec rubocop
rspec:
  extends: .ruby-base
  stage: test
  script:
    - bundle exec rbs collection install --frozen
    - RUBYOPT="-rrbs/test/setup" RBS_TEST_TARGET="SBOM::CycloneDX::*" bundle exec rspec
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  artifacts:
    when: always
    paths:
      - ${CI_JOB_ID}_junit.xml
      - ${CI_JOB_ID}_cobertura.xml
    reports:
      junit: ${CI_JOB_ID}_junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ${CI_JOB_ID}_cobertura.xml
