.ruby-base:
  tags:
    - runner-small
  image: $RUBY_IMAGE
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - ./vendor/ruby
  before_script:
    - ruby -v
    - bundle config set path vendor
    - bundle install --jobs=$(nproc) --retry=3
    - bundle exec rbs collection install
  variables:
    RUBY_IMAGE: ruby:3.3-alpine
lint:
  extends: .ruby-base
  stage: test
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - ./vendor/ruby
    - key: ${CI_PROJECT_PATH_SLUG}-${RUBY_IMAGE}-rubocop-cache
      paths:
        - $CI_PROJECT_DIR/rubocop-cache
  script:
    - bundle exec rubocop
rspec:
  extends: .ruby-base
  stage: test
  variables:
    RBS_TEST_TARGET: "SBOM::CycloneDX::*"
    RUBYOPT: "-rrbs/test/setup"
  script:
    - bundle exec rspec
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  artifacts:
    when: always
    paths:
      - ${CI_JOB_ID}_junit.xml
      - ${CI_JOB_ID}_cobertura.xml
    reports:
      junit: ${CI_JOB_ID}_junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ${CI_JOB_ID}_cobertura.xml
