require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\s*#:?\s.*'
    - '\s*#\$?\s.*'

Style/CommentAnnotation:
  Enabled: true
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW
    - NOTE
    - NOTE FOR REVIEWER
    - NOTE FOR AUTHOR

Layout/LeadingCommentSpace:
  AllowSteepAnnotation: true
  AllowRBSInlineAnnotation: true

Metrics/AbcSize:
  AllowedMethods:
    - valid?
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - valid?
Metrics/MethodLength:
  AllowedMethods:
    - initialize
    - valid?
Metrics/ParameterLists:
  CountKeywordArgs: false
RSpec/ExampleLength:
  Max: 16
RSpec/MultipleExpectations:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Max: 12
RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/sbom/cyclone_dx/record/*_spec.rb"
Style/AccessorGrouping:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/StructInheritance:
  Enabled: false
