module SBOM
  module CycloneDX
    class Advisory < ::Struct[untyped]
      def self.new: (
        url: uriString,
        ?title: String?
      ) -> instance

      def self.[]: (
        url: uriString,
        ?title: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :title, :url ]

      def members: () -> [ :title, :url ]

      def initialize: (url: uriString, ?title: String?) -> void

      attr_accessor title: String?

      attr_accessor url: uriString

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
