module SBOM
  module CycloneDX
    class Annotation < ::Struct[untyped]
      def self.new: (
        subjects: Set[String],
        annotator: Annotator,
        timestamp: DateTime,
        text: String,
        signature: SBOM::CycloneDX::signature,
        ?bom_ref: String?
      ) -> instance

      def self.[]: (
        subjects: Set[String],
        annotator: Annotator,
        timestamp: DateTime,
        text: String,
        signature: SBOM::CycloneDX::signature,
        ?bom_ref: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :subjects, :annotator, :timestamp, :text, :signature ]

      def members: () -> [ :bom_ref, :subjects, :annotator, :timestamp, :text, :signature ]

      def initialize: (
        subjects: Set[String],
        annotator: Annotator,
        timestamp: DateTime,
        text: String,
        signature: SBOM::CycloneDX::signature,
        ?bom_ref: String?
      ) -> void

      attr_accessor bom_ref: String?

      attr_accessor subjects: Set[String]

      attr_accessor annotator: Annotator

      attr_accessor timestamp: DateTime

      attr_accessor text: String

      attr_accessor signature: SBOM::CycloneDX::signature

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods

      class Annotator < ::Struct[untyped]
        def self.new: (
          ?organization: OrganizationalEntity?,
          ?individual: OrganizationalContact?,
          ?component: Component?,
          ?service: Service?
        ) -> instance

        def self.[]: (
          ?organization: OrganizationalEntity?,
          ?individual: OrganizationalContact?,
          ?component: Component?,
          ?service: Service?
        ) -> instance

        def self.keyword_init?: () -> true

        def self.members: () -> [ :organization, :individual, :component, :service ]

        def members: () -> [ :organization, :individual, :component, :service ]

        attr_accessor organization: OrganizationalEntity?

        attr_accessor individual: OrganizationalContact?

        attr_accessor component: Component?

        attr_accessor service: Service?

        include SBOM::CycloneDX::SchemaObject

        extend SBOM::CycloneDX::SchemaObject::ClassMethods
      end
    end
  end
end
