module SBOM
  module CycloneDX
    class Condition < ::Struct[untyped]
      def self.new: (
        ?description: String?,
        ?expression: String?,
        ?properties: String?
      ) -> instance

      def self.[]: (
        ?description: String?,
        ?expression: String?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :description, :expression, :properties ]

      def members: () -> [ :description, :expression, :properties ]

      attr_accessor description: String?

      attr_accessor expression: String?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
