module SBOM
  module CycloneDX
    class Copyright < ::Struct[untyped]
      def self.new: (text: String) -> instance

      def self.[]: (text: String) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :text ]

      def members: () -> [ :text ]

      def initialize: (text: String) -> void

      attr_accessor text: String

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
