module SBOM
  module CycloneDX
    class DataGovernance < ::Struct[untyped]
      def self.new: (
        ?custodians: DataGovernanceResponsibleParty?,
        ?stewards: DataGovernanceResponsibleParty?,
        ?owners: DataGovernanceResponsibleParty?
      ) -> instance

      def self.[]: (
        ?custodians: DataGovernanceResponsibleParty?,
        ?stewards: DataGovernanceResponsibleParty?,
        ?owners: DataGovernanceResponsibleParty?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :custodians, :stewards, :owners ]

      def members: () -> [ :custodians, :stewards, :owners ]

      attr_accessor custodians: DataGovernanceResponsibleParty?

      attr_accessor stewards: DataGovernanceResponsibleParty?

      attr_accessor owners: DataGovernanceResponsibleParty?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
