module SBOM
  module CycloneDX
    class DataGovernanceResponsibleParty < ::Struct[untyped]
      def self.new: (
        organization: OrganizationalEntity,
        ?contact: OrganizationalContact?
      ) -> instance | (
        ?organization: OrganizationalEntity?,
        contact: OrganizationalContact
      ) -> instance

      def self.[]: (
        organization: OrganizationalEntity,
        ?contact: OrganizationalContact?
      ) -> instance | (
        ?organization: OrganizationalEntity?,
        contact: OrganizationalContact
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :organization, :contact ]

      def members: () -> [ :organization, :contact ]

      def initialize: (
        organization: OrganizationalEntity,
        ?contact: OrganizationalContact?
      ) -> void | (
        ?organization: OrganizationalEntity?,
        contact: OrganizationalContact
      ) -> void

      attr_accessor organization: OrganizationalEntity?

      attr_accessor contact: OrganizationalContact?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
