module SBOM
  module CycloneDX
    class Definitions < ::Struct[untyped]
      def self.new: (?standards: Array[Standard]?) -> instance

      def self.[]: (?standards: Array[Standard]?) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :standards ]

      def members: () -> [ :standards ]

      attr_accessor standards: Array[Standard]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
