module SBOM
  module CycloneDX
    class Dependency < ::Struct[untyped]
      def self.new: (
        ref: String,
        ?depends_on: Array[String]?,
        ?provides: Array[String]?
      ) -> instance

      def self.[]: (
        ref: String,
        ?depends_on: Array[String]?,
        ?provides: Array[String]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :ref, :depends_on, :provides ]

      def members: () -> [ :ref, :depends_on, :provides ]

      def initialize: (
        ref: String,
        ?depends_on: Array[String]?,
        ?provides: Array[String]?
      ) -> void

      attr_accessor ref: String

      attr_accessor depends_on: Array[String]?

      attr_accessor provides: Array[String]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
