module SBOM
  module CycloneDX
    class Diff < ::Struct[untyped]
      def self.new: (
        ?text: Attachment?,
        ?url: uriString?
      ) -> instance

      def self.[]: (
        ?text: Attachment?,
        ?url: uriString?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :text, :url ]

      def members: () -> [ :text, :url ]

      attr_accessor text: Attachment?

      attr_accessor url: uriString?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
