module SBOM
  module CycloneDX
    class EnergyMeasure < ::Struct[untyped]
      def self.new: (?value: untyped, ?unit: untyped) -> instance

      def self.[]: (?value: untyped, ?unit: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :value, :unit ]

      def members: () -> [ :value, :unit ]

      attr_accessor value: untyped

      attr_accessor unit: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
