module SBOM
  module CycloneDX
    class EnergyMeasure < ::Struct[untyped]
      def self.new: (
        value: Float,
        unit: "kWh"
      ) -> instance

      def self.[]: (
        value: Float,
        unit: "kWh"
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :value, :unit ]

      def members: () -> [ :value, :unit ]

      def initialize: (value: Float) -> void

      attr_accessor value: Float

      attr_accessor unit: "kWh"

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
