module SBOM
  module CycloneDX
    class EnergyProvider < ::Struct[untyped]
      def self.new: (
        organization: OrganizationalEntity,
        energy_source: String,
        energy_provided: EnergyMeasure,
        ?bom_ref: String?,
        ?description: String?,
        ?external_references: Array[ExternalReference]?
      ) -> instance

      def self.[]: (
        organization: OrganizationalEntity,
        energy_source: String,
        energy_provided: EnergyMeasure,
        ?bom_ref: String?,
        ?description: String?,
        ?external_references: Array[ExternalReference]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :description, :organization, :energy_source, :energy_provided, :external_references ]

      def members: () -> [ :bom_ref, :description, :organization, :energy_source, :energy_provided, :external_references ]

      def initialize: (
        organization: OrganizationalEntity,
        energy_source: String,
        energy_provided: EnergyMeasure,
        ?bom_ref: String?,
        ?description: String?,
        ?external_references: Array[ExternalReference]?
      ) -> void

      attr_accessor bom_ref: String?

      attr_accessor description: String?

      attr_accessor organization: OrganizationalEntity

      attr_accessor energy_source: String

      attr_accessor energy_provided: EnergyMeasure

      attr_accessor external_references: Array[ExternalReference]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
