module SBOM
  module CycloneDX
    class EnvironmentalConsideration < ::Struct[untyped]
      def self.new: (
        ?energy_consumptions: Array[EnergyConsumption]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        ?energy_consumptions: Array[EnergyConsumption]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :energy_consumptions, :properties ]

      def members: () -> [ :energy_consumptions, :properties ]

      attr_accessor energy_consumptions: Array[EnergyConsumption]?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
