module SBOM
  module CycloneDX
    class Event < ::Struct[untyped]
      def self.new: (
        ?uid: String?,
        ?description: String?,
        ?time_received: dateTimeString?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        ?uid: String?,
        ?description: String?,
        ?time_received: dateTimeString?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :uid, :description, :time_received, :data, :source, :target, :properties ]

      def members: () -> [ :uid, :description, :time_received, :data, :source, :target, :properties ]

      attr_accessor uid: String?

      attr_accessor description: String?

      attr_accessor time_received: dateTimeString?

      attr_accessor data: Attachment?

      attr_accessor source: ResourceReferenceChoice?

      attr_accessor target: ResourceReferenceChoice?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
