module SBOM
  module CycloneDX
    class Event < ::Struct[untyped]
      def self.new: (?uid: untyped, ?description: untyped, ?time_received: untyped, ?data: untyped, ?source: untyped, ?target: untyped, ?properties: untyped) -> instance

      def self.[]: (?uid: untyped, ?description: untyped, ?time_received: untyped, ?data: untyped, ?source: untyped, ?target: untyped, ?properties: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :uid, :description, :time_received, :data, :source, :target, :properties ]

      def members: () -> [ :uid, :description, :time_received, :data, :source, :target, :properties ]

      attr_accessor uid: untyped

      attr_accessor description: untyped

      attr_accessor time_received: untyped

      attr_accessor data: untyped

      attr_accessor source: untyped

      attr_accessor target: untyped

      attr_accessor properties: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
