module SBOM
  module CycloneDX
    class ExternalReference < ::Struct[untyped]
      def self.new: (?url: untyped, ?comment: untyped, ?type: untyped, ?hashes: untyped) -> instance

      def self.[]: (?url: untyped, ?comment: untyped, ?type: untyped, ?hashes: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :url, :comment, :type, :hashes ]

      def members: () -> [ :url, :comment, :type, :hashes ]

      attr_accessor url: untyped

      attr_accessor comment: untyped

      attr_accessor type: untyped

      attr_accessor hashes: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
