module SBOM
  module CycloneDX
    class ExternalReference < ::Struct[untyped]
      def self.new: (
        url: uriString,
        type: String,
        ?comment: String?,
        ?hashes: Array[HashData]?
      ) -> instance

      def self.[]: (
        url: uriString,
        type: String,
        ?comment: String?,
        ?hashes: Array[HashData]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :url, :comment, :type, :hashes ]

      def members: () -> [ :url, :comment, :type, :hashes ]

      def initialize: (
        url: uriString,
        type: String,
        ?comment: String?,
        ?hashes: Array[HashData]?
      ) -> void

      attr_accessor url: uriString

      attr_accessor comment: String?

      attr_accessor type: String

      attr_accessor hashes: Array[HashData]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
