module SBOM
  module CycloneDX
    class FairnessAssessment < ::Struct[untyped]
      def self.new: (
        ?group_at_risk: String?,
        ?benefits: String?,
        ?harms: String?,
        ?mitigation_strategy: String?
      ) -> instance

      def self.[]: (
        ?group_at_risk: String?,
        ?benefits: String?,
        ?harms: String?,
        ?mitigation_strategy: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :group_at_risk, :benefits, :harms, :mitigation_strategy ]

      def members: () -> [ :group_at_risk, :benefits, :harms, :mitigation_strategy ]

      attr_accessor group_at_risk: String?

      attr_accessor benefits: String?

      attr_accessor harms: String?

      attr_accessor mitigation_strategy: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
