module SBOM
  module CycloneDX
    class FairnessAssessment < ::Struct[untyped]
      def self.new: (?group_at_risk: untyped, ?benefits: untyped, ?harms: untyped, ?mitigation_strategy: untyped) -> instance

      def self.[]: (?group_at_risk: untyped, ?benefits: untyped, ?harms: untyped, ?mitigation_strategy: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :group_at_risk, :benefits, :harms, :mitigation_strategy ]

      def members: () -> [ :group_at_risk, :benefits, :harms, :mitigation_strategy ]

      attr_accessor group_at_risk: untyped

      attr_accessor benefits: untyped

      attr_accessor harms: untyped

      attr_accessor mitigation_strategy: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
