module SBOM
  module CycloneDX
    class Formula < ::Struct[untyped]
      def self.new: (
        ?bom_ref: String?,
        ?components: Array[Component]?,
        ?services: Array[Service]?,
        ?workflows: Array[Workflow]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        ?bom_ref: String?,
        ?components: Array[Component]?,
        ?services: Array[Service]?,
        ?workflows: Array[Workflow]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :components, :services, :workflows, :properties ]

      def members: () -> [ :bom_ref, :components, :services, :workflows, :properties ]

      attr_accessor bom_ref: String?

      attr_accessor components: Array[Component]?

      attr_accessor services: Array[Service]?

      attr_accessor workflows: Array[Workflow]?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
