module SBOM
  module CycloneDX
    class Graphic < ::Struct[untyped]
      def self.new: (
        ?name: String?,
        ?image: Attachment?
      ) -> instance

      def self.[]: (
        ?name: String?,
        ?image: Attachment?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :name, :image ]

      def members: () -> [ :name, :image ]

      attr_accessor name: String?

      attr_accessor image: Attachment?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
