module SBOM
  module CycloneDX
    class GraphicsCollection < ::Struct[untyped]
      def self.new: (
        ?description: String?,
        ?collection: Array[Graphic]?
      ) -> instance

      def self.[]: (
        ?description: String?,
        ?collection: Array[Graphic]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :description, :collection ]

      def members: () -> [ :description, :collection ]

      attr_accessor description: String?

      attr_accessor collection: Array[Graphic]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
