module SBOM
  module CycloneDX
    class HashData < ::Struct[untyped]
      def self.new: (
        alg: String,
        content: String
      ) -> instance

      def self.[]: (
        alg: String,
        content: String
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :alg, :content ]

      def members: () -> [ :alg, :content ]

      def initialize: (alg: String, content: String) -> void

      attr_accessor alg: String

      attr_accessor content: String

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
