module SBOM
  module CycloneDX
    class IdentifiableAction < ::Struct[untyped]
      def self.new: (
        ?timestamp: DateTime?,
        ?name: String?,
        ?email: emailString?
      ) -> instance

      def self.[]: (
        ?timestamp: DateTime?,
        ?name: String?,
        ?email: emailString?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :timestamp, :name, :email ]

      def members: () -> [ :timestamp, :name, :email ]

      attr_accessor timestamp: DateTime

      attr_accessor name: String?

      attr_accessor email: emailString?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
