module SBOM
  module CycloneDX
    class InputOutputMLParameter < ::Struct[untyped]
      def self.new: (?format: String?) -> instance

      def self.[]: (?format: String?) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :format ]

      def members: () -> [ :format ]

      attr_accessor format: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
