module SBOM
  module CycloneDX
    class Input < ::Struct[untyped]
      def self.new: (
        resource: ResourceReferenceChoice,
        ?parameters: Array[Parameter]?,
        ?environment_vars: Array[Property | String]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance | (
        parameters: Array[Parameter],
        ?resource: ResourceReferenceChoice?,
        ?environment_vars: Array[Property | String]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance | (
        environment_vars: Array[Property | String],
        ?resource: ResourceReferenceChoice?,
        ?parameters: Array[Parameter]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance | (
        data: Attachment,
        ?resource: ResourceReferenceChoice?,
        ?parameters: Array[Parameter]?,
        ?environment_vars: Array[Property | String]?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        resource: ResourceReferenceChoice,
        ?parameters: Array[Parameter]?,
        ?environment_vars: Array[Property | String]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance | (
        parameters: Array[Parameter],
        ?resource: ResourceReferenceChoice?,
        ?environment_vars: Array[Property | String]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance | (
        environment_vars: Array[Property | String],
        ?resource: ResourceReferenceChoice?,
        ?parameters: Array[Parameter]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance | (
        data: Attachment,
        ?resource: ResourceReferenceChoice?,
        ?parameters: Array[Parameter]?,
        ?environment_vars: Array[Property | String]?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :source, :target, :resource, :parameters, :environment_vars, :data, :properties ]

      def members: () -> [ :source, :target, :resource, :parameters, :environment_vars, :data, :properties ]

      def initialize: (
        resource: ResourceReferenceChoice,
        ?parameters: Array[Parameter]?,
        ?environment_vars: Array[Property | String]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> void | (
        parameters: Array[Parameter],
        ?resource: ResourceReferenceChoice?,
        ?environment_vars: Array[Property | String]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> void | (
        environment_vars: Array[Property | String],
        ?resource: ResourceReferenceChoice?,
        ?parameters: Array[Parameter]?,
        ?data: Attachment?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> void | (
        data: Attachment,
        ?resource: ResourceReferenceChoice?,
        ?parameters: Array[Parameter]?,
        ?environment_vars: Array[Property | String]?,
        ?source: ResourceReferenceChoice?,
        ?target: ResourceReferenceChoice?,
        ?properties: Array[Property]?
      ) -> void

      attr_accessor source: ResourceReferenceChoice?

      attr_accessor target: ResourceReferenceChoice?

      attr_accessor resource: ResourceReferenceChoice?

      attr_accessor parameters: Array[Parameter]?

      attr_accessor environment_vars: Array[Property | String]?

      attr_accessor data: Attachment?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
