module SBOM
  module CycloneDX
    class Issue < ::Struct[untyped]
      def self.new: (
        type: String,
        ?id: String?,
        ?name: String?,
        ?description: String?,
        ?source: Source?,
        ?references: Array[uriString]
      ) -> instance

      def self.[]: (
        type: String,
        ?id: String?,
        ?name: String?,
        ?description: String?,
        ?source: Source?,
        ?references: Array[uriString]
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :type, :id, :name, :description, :source, :references ]

      def members: () -> [ :type, :id, :name, :description, :source, :references ]

      def initialize: (
        type: String,
        ?id: String?,
        ?name: String?,
        ?description: String?,
        ?source: Source?,
        ?references: Array[uriString]
      ) -> void

      attr_accessor type: untyped

      attr_accessor id: untyped

      attr_accessor name: untyped

      attr_accessor description: untyped

      attr_accessor source: untyped

      attr_accessor references: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods

      class Source < ::Struct[untyped]
        def self.new: (?name: String?, ?url: uriString?) -> instance

        def self.[]: (?name: String?, ?url: uriString?) -> instance

        def self.keyword_init?: () -> true

        def self.members: () -> [ :name, :url ]

        def members: () -> [ :name, :url ]

        attr_accessor name: String?

        attr_accessor url: uriString?

        include SBOM::CycloneDX::SchemaObject

        extend SBOM::CycloneDX::SchemaObject::ClassMethods
      end
    end
  end
end
