module SBOM
  module CycloneDX
    class Note < ::Struct[untyped]
      def self.new: (
        text: Attachment,
        ?locale: String?
      ) -> instance

      def self.[]: (
        text: Attachment,
        ?locale: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :locale, :text ]

      def members: () -> [ :locale, :text ]

      def initialize: (
        text: Attachment,
        ?locale: String?
      ) -> void

      attr_accessor locale: String?

      attr_accessor text: Attachment

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
