module SBOM
  module CycloneDX
    class OrganizationalEntity < ::Struct[untyped]
      def self.new: (?bom_ref: untyped, ?name: untyped, ?address: untyped, ?url: untyped, ?contact: untyped) -> instance

      def self.[]: (?bom_ref: untyped, ?name: untyped, ?address: untyped, ?url: untyped, ?contact: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :name, :address, :url, :contact ]

      def members: () -> [ :bom_ref, :name, :address, :url, :contact ]

      attr_accessor bom_ref: untyped

      attr_accessor name: untyped

      attr_accessor address: untyped

      attr_accessor url: untyped

      attr_accessor contact: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
