module SBOM
  module CycloneDX
    class OrganizationalContact < ::Struct[untyped]
      def self.new: (
        ?bom_ref: String?,
        ?name: String?,
        ?email: emailString?,
        ?phone: String?
      ) -> instance

      def self.[]: (
        ?bom_ref: String?,
        ?name: String?,
        ?email: emailString?,
        ?phone: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :name, :email, :phone ]

      def members: () -> [ :bom_ref, :name, :email, :phone ]

      attr_accessor bom_ref: String?

      attr_accessor name: String?

      attr_accessor email: emailString?

      attr_accessor phone: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
