module SBOM
  module CycloneDX
    class OrganizationalEntity < ::Struct[untyped]
      def self.new: (
        ?bom_ref: String?,
        ?name: String?,
        ?address: PostalAddress?,
        ?url: Array[uriString]?,
        ?contact: Array[OrganizationalContact]?
      ) -> instance

      def self.[]: (
        ?bom_ref: String?,
        ?name: String?,
        ?address: PostalAddress?,
        ?url: Array[uriString]?,
        ?contact: Array[OrganizationalContact]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :name, :address, :url, :contact ]

      def members: () -> [ :bom_ref, :name, :address, :url, :contact ]

      attr_accessor bom_ref: String?

      attr_accessor name: String?

      attr_accessor address: PostalAddress?

      attr_accessor url: Array[uriString]?

      attr_accessor contact: Array[OrganizationalContact]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
