module SBOM
  module CycloneDX
    class Parameter < ::Struct[untyped]
      def self.new: (
        ?name: String?,
        ?value: String?,
        ?data_type: String?
      ) -> instance

      def self.[]: (
        ?name: String?,
        ?value: String?,
        ?data_type: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :name, :value, :data_type ]

      def members: () -> [ :name, :value, :data_type ]

      attr_accessor name: String?

      attr_accessor value: String?

      attr_accessor data_type: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
