module SBOM
  module CycloneDX
    class Patch < ::Struct[untyped]
      def self.new: (
        type: String,
        ?diff: Diff?,
        ?resolves: Array[Issue]?
      ) -> instance

      def self.[]: (
        type: String,
        ?diff: Diff?,
        ?resolves: Array[Issue]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :type, :diff, :resolves ]

      def members: () -> [ :type, :diff, :resolves ]

      def initialize: (
        type: String,
        ?diff: Diff?,
        ?resolves: Array[Issue]?
      ) -> void

      attr_accessor type: String

      attr_accessor diff: Diff?

      attr_accessor resolves: Array[Issue]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
