module SBOM
  module CycloneDX
    class PerformanceMetric < ::Struct[untyped]
      def self.new: (
        ?type: String?,
        ?value: String?,
        ?slice: String?,
        ?confidence_interval: ConfidenceInterval?
      ) -> instance

      def self.[]: (
        ?type: String?,
        ?value: String?,
        ?slice: String?,
        ?confidence_interval: ConfidenceInterval?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :type, :value, :slice, :confidence_interval ]

      def members: () -> [ :type, :value, :slice, :confidence_interval ]

      attr_accessor type: String?

      attr_accessor value: String?

      attr_accessor slice: String?

      attr_accessor confidence_interval: ConfidenceInterval?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods

      class ConfidenceInterval < ::Struct[untyped]
        def self.new: (
          ?lower_bound: String?,
          ?upper_bound: String?
        ) -> instance

        def self.[]: (
          ?lower_bound: String?,
          ?upper_bound: String?
        ) -> instance

        def self.keyword_init?: () -> true

        def self.members: () -> [ :lower_bound, :upper_bound ]

        def members: () -> [ :lower_bound, :upper_bound ]

        attr_accessor lower_bound: String?

        attr_accessor upper_bound: String?

        include SBOM::CycloneDX::SchemaObject

        extend SBOM::CycloneDX::SchemaObject::ClassMethods
      end
    end
  end
end
