module SBOM
  module CycloneDX
    class PostalAddress < ::Struct[untyped]
      def self.new: (
        ?bom_ref: String?,
        ?country: String?,
        ?region: String?,
        ?locality: String?,
        ?post_office_box_number: String?,
        ?postal_code: String?,
        ?street_address: String?
      ) -> instance

      def self.[]: (
        ?bom_ref: String?,
        ?country: String?,
        ?region: String?,
        ?locality: String?,
        ?post_office_box_number: String?,
        ?postal_code: String?,
        ?street_address: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :country, :region, :locality, :post_office_box_number, :postal_code, :street_address ]

      def members: () -> [ :bom_ref, :country, :region, :locality, :post_office_box_number, :postal_code, :street_address ]

      attr_accessor bom_ref: String?

      attr_accessor country: String?

      attr_accessor region: String?

      attr_accessor locality: String?

      attr_accessor post_office_box_number: String?

      attr_accessor postal_code: String?

      attr_accessor street_address: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
