module SBOM
  module CycloneDX
    class Property < ::Struct[untyped]
      def self.new: (
        name: String,
        ?value: String?
      ) -> instance

      def self.[]: (
        name: String,
        ?value: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :name, :value ]

      def members: () -> [ :name, :value ]

      def initialize: (
        name: String,
        ?value: String?
      ) -> void

      attr_accessor name: String

      attr_accessor value: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
