module SBOM
  module CycloneDX
    class Rating < ::Struct[untyped]
      def self.new: (
        ?source: VulnerabilitySource?,
        ?score: Float?,
        ?severity: String?,
        ?score_method: String?,
        ?vector: String?,
        ?justification: String?
      ) -> instance

      def self.[]: (
        ?source: VulnerabilitySource?,
        ?score: Float?,
        ?severity: String?,
        ?score_method: String?,
        ?vector: String?,
        ?justification: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :source, :score, :severity, :score_method, :vector, :justification ]

      def members: () -> [ :source, :score, :severity, :score_method, :vector, :justification ]

      attr_accessor source: VulnerabilitySource?

      attr_accessor score: Float?

      attr_accessor severity: String?

      attr_accessor score_method: String?

      attr_accessor vector: String?

      attr_accessor justification: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
