module SBOM
  module CycloneDX
    class Rating < ::Struct[untyped]
      def self.new: (?source: untyped, ?score: untyped, ?severity: untyped, ?score_method: untyped, ?vector: untyped, ?justification: untyped) -> instance

      def self.[]: (?source: untyped, ?score: untyped, ?severity: untyped, ?score_method: untyped, ?vector: untyped, ?justification: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :source, :score, :severity, :score_method, :vector, :justification ]

      def members: () -> [ :source, :score, :severity, :score_method, :vector, :justification ]

      attr_accessor source: untyped

      attr_accessor score: untyped

      attr_accessor severity: untyped

      attr_accessor score_method: untyped

      attr_accessor vector: untyped

      attr_accessor justification: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
