module SBOM
  module CycloneDX
    class ResourceReferenceChoice < ::Struct[untyped]
      def self.new: (
        ref: String,
        ?external_reference: ExternalReference?
      ) -> instance | (
        external_reference: ExternalReference,
        ?ref: String?
      ) -> instance

      def self.[]: (
        ref: String,
        ?external_reference: ExternalReference?
      ) -> instance | (
        external_reference: ExternalReference,
        ?ref: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :ref, :external_reference ]

      def members: () -> [ :ref, :external_reference ]

      def initialize: (
        ref: String,
        ?external_reference: ExternalReference?
      ) -> void | (
        external_reference: ExternalReference,
        ?ref: String?
      ) -> void

      attr_accessor ref: String?

      attr_accessor external_reference: ExternalReference?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
