module SBOM
  module CycloneDX
    class Risk < ::Struct[untyped]
      def self.new: (
        ?name: String?,
        ?mitigation_strategy: String?
      ) -> instance

      def self.[]: (
        ?name: String?,
        ?mitigation_strategy: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :name, :mitigation_strategy ]

      def members: () -> [ :name, :mitigation_strategy ]

      attr_accessor name: String?

      attr_accessor mitigation_strategy: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
