module SBOM
  module CycloneDX
    class Root < ::Struct[untyped]
      def self.new: (
        version: Integer,
        ?serial_number: String?,
        ?metadata: Metadata?,
        ?components: Array[Component]?,
        ?services: Array[Service]?,
        ?external_references: Array[ExternalReference]?,
        ?dependencies: Array[Dependency]?,
        ?compositions: Array[Composition]?,
        ?vulnerabilities: Array[Vulnerability]?,
        ?annotations: Array[Annotation]?,
        ?formulation: Array[Formula]?,
        ?declarations: Declarations?,
        ?definitions: Definitions?,
        ?properties: Array[Property]?,
        ?signature: signature?
      ) -> instance

      def self.[]: (
        version: Integer,
        ?serial_number: String?,
        ?metadata: Metadata?,
        ?components: Array[Component]?,
        ?services: Array[Service]?,
        ?external_references: Array[ExternalReference]?,
        ?dependencies: Array[Dependency]?,
        ?compositions: Array[Composition]?,
        ?vulnerabilities: Array[Vulnerability]?,
        ?annotations: Array[Annotation]?,
        ?formulation: Array[Formula]?,
        ?declarations: Declarations?,
        ?definitions: Definitions?,
        ?properties: Array[Property]?,
        ?signature: signature?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :serial_number, :version, :metadata, :components, :services, :external_references, :dependencies, :compositions, :vulnerabilities, :annotations, :formulation, :declarations, :definitions, :properties, :signature, :bom_format, :spec_version ]

      def members: () -> [ :serial_number, :version, :metadata, :components, :services, :external_references, :dependencies, :compositions, :vulnerabilities, :annotations, :formulation, :declarations, :definitions, :properties, :signature, :bom_format, :spec_version ]

      def initialize: (
        version: Integer,
        ?serial_number: String?,
        ?metadata: Metadata?,
        ?components: Array[Component]?,
        ?services: Array[Service]?,
        ?external_references: Array[ExternalReference]?,
        ?dependencies: Array[Dependency]?,
        ?compositions: Array[Composition]?,
        ?vulnerabilities: Array[Vulnerability]?,
        ?annotations: Array[Annotation]?,
        ?formulation: Array[Formula]?,
        ?declarations: Declarations?,
        ?definitions: Definitions?,
        ?properties: Array[Property]?,
        ?signature: signature?
      ) -> void

      attr_accessor serial_number: String?

      attr_accessor version: Integer

      attr_accessor metadata: Metadata?

      attr_accessor components: Array[Component]?

      attr_accessor services: Array[Service]?

      attr_accessor external_references: Array[ExternalReference]?

      attr_accessor dependencies: Array[Dependency]?

      attr_accessor compositions: Array[Composition]?

      attr_accessor vulnerabilities: Array[Vulnerability]?

      attr_accessor annotations: Array[Annotation]?

      attr_accessor formulation: Array[Formula]?

      attr_accessor declarations: Declarations?

      attr_accessor definitions: Definitions?

      attr_accessor properties: Array[Property]?

      attr_accessor signature: signature?

      attr_reader bom_format: "CycloneDX"

      attr_reader spec_version: "1.6"

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
