module SBOM
  module CycloneDX
    class Service < ::Struct[untyped]
      def self.new: (
        name: String,
        ?bom_ref: String?,
        ?provider: OrganizationalEntity?,
        ?group: String?,
        ?version: String?,
        ?description: String?,
        ?endpoints: Array[uriString]?,
        ?authenticated: bool?,
        ?x_trust_boundary: bool?,
        ?trust_zone: String?,
        ?data: Array[ServiceData]?,
        ?licenses: Array[licenseChoice]?,
        ?external_references: Array[ExternalReference]?,
        ?services: Array[Service]?,
        ?release_notes: ReleaseNotes?,
        ?properties: Array[Property]?,
        ?tags: Array[String]?,
        ?signature: signature?
      ) -> instance

      def self.[]: (
        name: String,
        ?bom_ref: String?,
        ?provider: OrganizationalEntity?,
        ?group: String?,
        ?version: String?,
        ?description: String?,
        ?endpoints: Array[uriString]?,
        ?authenticated: bool?,
        ?x_trust_boundary: bool?,
        ?trust_zone: String?,
        ?data: Array[ServiceData]?,
        ?licenses: Array[licenseChoice]?,
        ?external_references: Array[ExternalReference]?,
        ?services: Array[Service]?,
        ?release_notes: ReleaseNotes?,
        ?properties: Array[Property]?,
        ?tags: Array[String]?,
        ?signature: signature?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :provider, :group, :name, :version, :description, :endpoints, :authenticated, :x_trust_boundary, :trust_zone, :data, :licenses, :external_references, :services, :release_notes, :properties, :tags, :signature ]

      def members: () -> [ :bom_ref, :provider, :group, :name, :version, :description, :endpoints, :authenticated, :x_trust_boundary, :trust_zone, :data, :licenses, :external_references, :services, :release_notes, :properties, :tags, :signature ]

      def initialize: (
        name: String,
        ?bom_ref: String?,
        ?provider: OrganizationalEntity?,
        ?group: String?,
        ?version: String?,
        ?description: String?,
        ?endpoints: Array[uriString]?,
        ?authenticated: bool?,
        ?x_trust_boundary: bool?,
        ?trust_zone: String?,
        ?data: Array[ServiceData]?,
        ?licenses: Array[licenseChoice]?,
        ?external_references: Array[ExternalReference]?,
        ?services: Array[Service]?,
        ?release_notes: ReleaseNotes?,
        ?properties: Array[Property]?,
        ?tags: Array[String]?,
        ?signature: signature?
      ) -> void

      attr_accessor bom_ref: String?

      attr_accessor provider: OrganizationalEntity?

      attr_accessor group: String?

      attr_accessor name: String

      attr_accessor version: String?

      attr_accessor description: String?

      attr_accessor endpoints: Array[uriString]?

      attr_accessor authenticated: bool?

      attr_accessor x_trust_boundary: bool?

      attr_accessor trust_zone: String?

      attr_accessor data: Array[ServiceData]?

      attr_accessor licenses: Array[licenseChoice]?

      attr_accessor external_references: Array[ExternalReference]?

      attr_accessor services: Array[Service]?

      attr_accessor release_notes: ReleaseNotes?

      attr_accessor properties: Array[Property]?

      attr_accessor tags: Array[String]?

      attr_accessor signature: signature?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
