module SBOM
  module CycloneDX
    class Service < ::Struct[untyped]
      def self.new: (?bom_ref: untyped, ?provider: untyped, ?group: untyped, ?name: untyped, ?version: untyped, ?description: untyped, ?endpoints: untyped, ?authenticated: untyped, ?x_trust_boundary: untyped, ?trust_zone: untyped, ?data: untyped, ?licenses: untyped, ?external_references: untyped, ?services: untyped, ?release_notes: untyped, ?properties: untyped, ?tags: untyped, ?signature: untyped) -> instance

      def self.[]: (?bom_ref: untyped, ?provider: untyped, ?group: untyped, ?name: untyped, ?version: untyped, ?description: untyped, ?endpoints: untyped, ?authenticated: untyped, ?x_trust_boundary: untyped, ?trust_zone: untyped, ?data: untyped, ?licenses: untyped, ?external_references: untyped, ?services: untyped, ?release_notes: untyped, ?properties: untyped, ?tags: untyped, ?signature: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :provider, :group, :name, :version, :description, :endpoints, :authenticated, :x_trust_boundary, :trust_zone, :data, :licenses, :external_references, :services, :release_notes, :properties, :tags, :signature ]

      def members: () -> [ :bom_ref, :provider, :group, :name, :version, :description, :endpoints, :authenticated, :x_trust_boundary, :trust_zone, :data, :licenses, :external_references, :services, :release_notes, :properties, :tags, :signature ]

      attr_accessor bom_ref: untyped

      attr_accessor provider: untyped

      attr_accessor group: untyped

      attr_accessor name: untyped

      attr_accessor version: untyped

      attr_accessor description: untyped

      attr_accessor endpoints: untyped

      attr_accessor authenticated: untyped

      attr_accessor x_trust_boundary: untyped

      attr_accessor trust_zone: untyped

      attr_accessor data: untyped

      attr_accessor licenses: untyped

      attr_accessor external_references: untyped

      attr_accessor services: untyped

      attr_accessor release_notes: untyped

      attr_accessor properties: untyped

      attr_accessor tags: untyped

      attr_accessor signature: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
