module SBOM
  module CycloneDX
    class Step < ::Struct[untyped]
      def self.new: (
        ?name: String?,
        ?description: String?,
        ?commands: Array[Command]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        ?name: String?,
        ?description: String?,
        ?commands: Array[Command]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :name, :description, :commands, :properties ]

      def members: () -> [ :name, :description, :commands, :properties ]

      attr_accessor name: String?

      attr_accessor description: String?

      attr_accessor commands: Array[Command]?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
