module SBOM
  module CycloneDX
    class SWID < ::Struct[untyped]
      def self.new: (
        tag_id: String,
        name: String,
        ?version: String?,
        ?tag_version: Integer?,
        ?patch: bool?,
        ?text: Attachment?,
        ?url: uriString?
      ) -> instance

      def self.[]: (
        tag_id: String,
        name: String,
        ?version: String?,
        ?tag_version: Integer?,
        ?patch: bool?,
        ?text: Attachment?,
        ?url: uriString?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :tag_id, :name, :version, :tag_version, :patch, :text, :url ]

      def members: () -> [ :tag_id, :name, :version, :tag_version, :patch, :text, :url ]

      def initialize: (
        tag_id: String,
        name: String,
        ?version: String?,
        ?tag_version: Integer?,
        ?patch: bool?,
        ?text: Attachment?,
        ?url: uriString?
      ) -> void

      attr_accessor tag_id: String

      attr_accessor name: String

      attr_accessor version: String?

      attr_accessor tag_version: Integer?

      attr_accessor patch: bool?

      attr_accessor text: Attachment?

      attr_accessor url: uriString?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
