module SBOM
  module CycloneDX
    class Task < ::Struct[untyped]
      def self.new: (
        bom_ref: String,
        uid: String,
        ?name: String?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?task_types: Array[String]?,
        ?trigger: Trigger?,
        ?steps: Array[Step]?,
        ?inputs: Array[Input]?,
        ?outputs: Array[Output]?,
        ?time_start: dateTimeString?,
        ?time_end: dateTimeString?,
        ?workspaces: Array[Workspace]?,
        ?runtime_topology: Array[Dependency]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        bom_ref: String,
        uid: String,
        ?name: String?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?task_types: Array[String]?,
        ?trigger: Trigger?,
        ?steps: Array[Step]?,
        ?inputs: Array[Input]?,
        ?outputs: Array[Output]?,
        ?time_start: dateTimeString?,
        ?time_end: dateTimeString?,
        ?workspaces: Array[Workspace]?,
        ?runtime_topology: Array[Dependency]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :uid, :name, :description, :resource_references, :task_types, :trigger, :steps, :inputs, :outputs, :time_start, :time_end, :workspaces, :runtime_topology, :properties ]

      def members: () -> [ :bom_ref, :uid, :name, :description, :resource_references, :task_types, :trigger, :steps, :inputs, :outputs, :time_start, :time_end, :workspaces, :runtime_topology, :properties ]

      def initialize: (
        bom_ref: String,
        uid: String,
        ?name: String?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?task_types: Array[String]?,
        ?trigger: Trigger?,
        ?steps: Array[Step]?,
        ?inputs: Array[Input]?,
        ?outputs: Array[Output]?,
        ?time_start: dateTimeString?,
        ?time_end: dateTimeString?,
        ?workspaces: Array[Workspace]?,
        ?runtime_topology: Array[Dependency]?,
        ?properties: Array[Property]?
      ) -> void

      attr_accessor bom_ref: String

      attr_accessor uid: String

      attr_accessor name: String?

      attr_accessor description: String?

      attr_accessor resource_references: Array[ResourceReferenceChoice]?

      attr_accessor task_types: Array[String]?

      attr_accessor trigger: Trigger?

      attr_accessor steps: Array[Step]?

      attr_accessor inputs: Array[Input]?

      attr_accessor outputs: Array[Output]?

      attr_accessor time_start: dateTimeString?

      attr_accessor time_end: dateTimeString?

      attr_accessor workspaces: Array[Workspace]?

      attr_accessor runtime_topology: Array[Dependency]?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
