module SBOM
  module CycloneDX
    class Tools < ::Struct[untyped]
      def self.new: (
        ?components: Array[Component]?,
        ?services: Array[Service]?
      ) -> instance

      def self.[]: (
        ?components: Array[Component]?,
        ?services: Array[Service]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :components, :services ]

      def members: () -> [ :components, :services ]

      attr_accessor components: Array[Component]?

      attr_accessor services: Array[Service]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
