module SBOM
  module CycloneDX
    class Trigger < ::Struct[untyped]
      def self.new: (
        bom_ref: String,
        uid: String,
        type: String,
        ?name: String?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?event: Event?,
        ?conditions: Array[Condition]?,
        ?time_activated: dateTimeString?,
        ?inputs: Array[Input]?,
        ?outputs: Array[Output]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        bom_ref: String,
        uid: String,
        type: String,
        ?name: String?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?event: Event?,
        ?conditions: Array[Condition]?,
        ?time_activated: dateTimeString?,
        ?inputs: Array[Input]?,
        ?outputs: Array[Output]?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :uid, :name, :description, :resource_references, :type, :event, :conditions, :time_activated, :inputs, :outputs, :properties ]

      def members: () -> [ :bom_ref, :uid, :name, :description, :resource_references, :type, :event, :conditions, :time_activated, :inputs, :outputs, :properties ]

      def initialize: (
        bom_ref: String,
        uid: String,
        type: String,
        ?name: String?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?event: Event?,
        ?conditions: Array[Condition]?,
        ?time_activated: dateTimeString?,
        ?inputs: Array[Input]?,
        ?outputs: Array[Output]?,
        ?properties: Array[Property]?
      ) -> void

      attr_accessor bom_ref: String

      attr_accessor uid: String

      attr_accessor type: String

      attr_accessor name: String?

      attr_accessor description: String?

      attr_accessor resource_references: Array[ResourceReferenceChoice]?

      attr_accessor event: Event?

      attr_accessor conditions: Array[Condition]?

      attr_accessor time_activated: dateTimeString?

      attr_accessor inputs: Array[Input]?

      attr_accessor outputs: Array[Output]?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
