module SBOM
  module CycloneDX
    class Version < ::Struct[untyped]
      def self.new: (
        version: String,
        ?range: String?,
        ?status: String?
      ) -> instance | (
        range: String,
        ?version: String?,
        ?status: String?
      ) -> instance

      def self.[]: (
        version: String,
        ?range: String?,
        ?status: String?
      ) -> instance | (
        range: String,
        ?version: String?,
        ?status: String?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :version, :range, :status ]

      def members: () -> [ :version, :range, :status ]

      def initialize: (
        version: String,
        ?range: String?,
        ?status: String?
      ) -> void | (
        range: String,
        ?version: String?,
        ?status: String?
      ) -> void

      attr_accessor version: String?

      attr_accessor range: String?

      attr_accessor status: String?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
