module SBOM
  module CycloneDX
    class Volume < ::Struct[untyped]
      def self.new: (?uid: untyped, ?name: untyped, ?mode: untyped, ?path: untyped, ?size_allocated: untyped, ?persistent: untyped, ?remote: untyped, ?properties: untyped) -> instance

      def self.[]: (?uid: untyped, ?name: untyped, ?mode: untyped, ?path: untyped, ?size_allocated: untyped, ?persistent: untyped, ?remote: untyped, ?properties: untyped) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :uid, :name, :mode, :path, :size_allocated, :persistent, :remote, :properties ]

      def members: () -> [ :uid, :name, :mode, :path, :size_allocated, :persistent, :remote, :properties ]

      attr_accessor uid: untyped

      attr_accessor name: untyped

      attr_accessor mode: untyped

      attr_accessor path: untyped

      attr_accessor size_allocated: untyped

      attr_accessor persistent: untyped

      attr_accessor remote: untyped

      attr_accessor properties: untyped

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
