module SBOM
  module CycloneDX
    class Workspace < ::Struct[untyped]
      def self.new: (
        bom_ref: String,
        uid: String,
        ?name: String?,
        ?aliases: Array[String]?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?access_mode: String?,
        ?mount_path: String?,
        ?managed_data_type: String?,
        ?volume_request: String?,
        ?volume: Volume?,
        ?properties: Array[Property]?
      ) -> instance

      def self.[]: (
        bom_ref: String,
        uid: String,
        ?name: String?,
        ?aliases: Array[String]?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?access_mode: String?,
        ?mount_path: String?,
        ?managed_data_type: String?,
        ?volume_request: String?,
        ?volume: Volume?,
        ?properties: Array[Property]?
      ) -> instance

      def self.keyword_init?: () -> true

      def self.members: () -> [ :bom_ref, :uid, :name, :aliases, :description, :resource_references, :access_mode, :mount_path, :managed_data_type, :volume_request, :volume, :properties ]

      def members: () -> [ :bom_ref, :uid, :name, :aliases, :description, :resource_references, :access_mode, :mount_path, :managed_data_type, :volume_request, :volume, :properties ]

      def initialize: (
        bom_ref: String,
        uid: String,
        ?name: String?,
        ?aliases: Array[String]?,
        ?description: String?,
        ?resource_references: Array[ResourceReferenceChoice]?,
        ?access_mode: String?,
        ?mount_path: String?,
        ?managed_data_type: String?,
        ?volume_request: String?,
        ?volume: Volume?,
        ?properties: Array[Property]?
      ) -> void

      attr_accessor bom_ref: String

      attr_accessor uid: String

      attr_accessor name: String?

      attr_accessor aliases: Array[String]?

      attr_accessor description: String?

      attr_accessor resource_references: Array[ResourceReferenceChoice]?

      attr_accessor access_mode: String?

      attr_accessor mount_path: String?

      attr_accessor managed_data_type: String?

      attr_accessor volume_request: String?

      attr_accessor volume: Volume?

      attr_accessor properties: Array[Property]?

      include SBOM::CycloneDX::SchemaObject

      extend SBOM::CycloneDX::SchemaObject::ClassMethods
    end
  end
end
