module SBOM
  module CycloneDX
    module Record
      class Advisory < Base
        def initialize: (?title: String?, url: uri) -> void

        @title: String?
        def title: () -> String?
        def title=: (String?) -> String?
        def title?: () -> bool
        def title_valid?: () -> bool

        @url: uri
        def url: () -> uri
        def url=: (uri) -> uri
        def url?: () -> bool
        def url_valid?: () -> bool
      end
    end
  end
end
