module SBOM
  module CycloneDX
    module Record
      class Attachment < Base
        def initialize: (content: String, ?content_type: String) -> void

        @content_type: String
        def content_type: () -> String
        def content_type=: (String) -> String
        def content_type?: () -> bool
        def content_type_valid?: () -> bool

        @content: String
        def content: () -> String
        def content=: (String) -> String
        def content?: () -> bool
        def content_valid?: () -> bool

        type encodingConst = "base64"
        @encoding: encodingConst
        def encoding: () -> encodingConst
        def encoding?: () -> true
        def encoding_valid?: () -> true
      end
    end
  end
end
