module SBOM
  module CycloneDX
    module Record
      class Diff < Base
        def initialize: (?text: Attachment?, ?url: uri?) -> void

        def text: () -> Attachment?
        def text=: (Attachment?) -> Attachment?
        def text?: () -> bool
        def text_valid?: () -> bool

        def url: () -> uri?
        def url=: (uri?) -> uri?
        def url?: () -> bool
        def url_valid?: () -> bool
      end
    end
  end
end
