module SBOM
  module CycloneDX
    module Record
      class EnvironmentalConsideration < Base
        def initialize: (?energy_consumptions: Array[EnergyConsumption]?, ?properties: Array[Property]?) -> void

        def energy_consumptions: () -> Array[EnergyConsumption]?
        def energy_consumptions=: (Array[EnergyConsumption]?) -> Array[EnergyConsumption]?
        def energy_consumptions?: () -> bool
        def energy_consumptions_valid?: () -> bool

        def properties: () -> Array[Property]?
        def properties=: (Array[Property]?) -> Array[Property]?
        def properties?: () -> bool
        def properties_valid?: () -> bool
      end
    end
  end
end
