module SBOM
  module CycloneDX
    module Record
      class Event < Base
        def initialize: (?uid: String?, ?description: String?, ?time_received: dateTime?, ?data: Attachment?, ?source: ResourceReferenceChoice?, ?target: ResourceReferenceChoice?, ?properties: Array[Property]?) -> void

        def uid: () -> String?
        def uid=: (String?) -> String?
        def uid?: () -> bool
        def uid_valid?: () -> bool

        def description: () -> String?
        def description=: (String?) -> String?
        def description?: () -> bool
        def description_valid?: () -> bool

        def time_received: () -> dateTime?
        def time_received=: (dateTime?) -> dateTime?
        def time_received?: () -> bool
        def time_received_valid?: () -> bool

        def data: () -> Attachment?
        def data=: (Attachment?) -> Attachment?
        def data?: () -> bool
        def data_valid?: () -> bool

        def source: () -> ResourceReferenceChoice?
        def source=: (ResourceReferenceChoice?) -> ResourceReferenceChoice?
        def source?: () -> bool
        def source_valid?: () -> bool

        def target: () -> ResourceReferenceChoice?
        def target=: (ResourceReferenceChoice?) -> ResourceReferenceChoice?
        def target?: () -> bool
        def target_valid?: () -> bool

        def properties: () -> Array[Property]?
        def properties=: (Array[Property]?) -> Array[Property]?
        def properties?: () -> bool
        def properties_valid?: () -> bool
      end
    end
  end
end
