module SBOM
  module CycloneDX
    module Record
      class FairnessAssessment < Base
        def initialize: (?group_at_risk: String?, ?benefits: String?, ?harms: String?, ?mitigation_strategy: String?) -> void

        def group_at_risk: () -> String?
        def group_at_risk=: (String?) -> String?
        def group_at_risk?: () -> bool
        def group_at_risk_valid?: () -> bool

        def benefits: () -> String?
        def benefits=: (String?) -> String?
        def benefits?: () -> bool
        def benefits_valid?: () -> bool

        def harms: () -> String?
        def harms=: (String?) -> String?
        def harms?: () -> bool
        def harms_valid?: () -> bool

        def mitigation_strategy: () -> String?
        def mitigation_strategy=: (String?) -> String?
        def mitigation_strategy?: () -> bool
        def mitigation_strategy_valid?: () -> bool
      end
    end
  end
end
