module SBOM
  module CycloneDX
    module Record
      class HashData < Base
        def initialize: (alg: String, content: String) -> void

        def alg: () -> String
        def alg=: (String) -> String
        def alg?: () -> bool
        def alg_valid?: () -> bool

        def content: () -> String
        def content=: (String) -> String
        def content?: () -> bool
        def content_valid?: () -> bool
      end
    end
  end
end
