module SBOM
  module CycloneDX
    module Record
      class InputOutputMLParameter < Base
        def initialize: (?format: String?) -> void

        def format: () -> String?
        def format=: (String?) -> String?
        def format?: () -> bool
        def format_valid?: () -> bool
      end
    end
  end
end
