module SBOM
  module CycloneDX
    module Record
      class Issue < Base
        class Source < Base
          def initialize: (?name: String?, ?url: uri?) -> void

          def name: () -> String?
          def name=: (String?) -> String?
          def name?: () -> bool
          def name_valid?: () -> bool

          def url: () -> uri?
          def url=: (uri?) -> uri?
          def url?: () -> bool
          def url_valid?: () -> bool
        end

        def initialize: (type: String, ?id: String?, ?name: String?, ?description: String?, ?source: Source?, ?references: Array[uri]?) -> void

        def type: () -> String
        def type=: (String) -> String
        def type?: () -> bool
        def type_valid?: () -> bool

        def id: () -> String?
        def id=: (String?) -> String?
        def id?: () -> bool
        def id_valid?: () -> bool

        def name: () -> String?
        def name=: (String?) -> String?
        def name?: () -> bool
        def name_valid?: () -> bool

        def description: () -> String?
        def description=: (String?) -> String?
        def description?: () -> bool
        def description_valid?: () -> bool

        def source: () -> Source?
        def source=: (Source?) -> Source?
        def source?: () -> bool
        def source_valid?: () -> bool

        def references: () -> Array[uri]?
        def references=: (Array[uri]?) -> Array[uri]?
        def references?: () -> bool
        def references_valid?: () -> bool
      end
    end
  end
end
