module SBOM
  module CycloneDX
    module Record
      class OrganizationalContact < Base
        def initialize: (?bom_ref: String?, ?name: String?, ?email: emailAddress?, ?phone: String?) -> void

        def bom_ref: () -> String?
        def bom_ref=: (String?) -> String?
        def bom_ref?: () -> bool
        def bom_ref_valid?: () -> bool

        def name: () -> String?
        def name=: (String?) -> String?
        def name?: () -> bool
        def name_valid?: () -> bool

        def email: () -> emailAddress?
        def email=: (emailAddress?) -> emailAddress?
        def email?: () -> bool
        def email_valid?: () -> bool

        def phone: () -> String?
        def phone=: (String?) -> String?
        def phone?: () -> bool
        def phone_valid?: () -> bool
      end
    end
  end
end
