module SBOM
  module CycloneDX
    module Record
      class Risk < Base
        def initialize: (?name: String?, ?mitigation_strategy: String?) -> void

        def name: () -> String?
        def name=: (String?) -> String?
        def name?: () -> bool
        def name_valid?: () -> bool

        def mitigation_strategy: () -> String?
        def mitigation_strategy=: (String?) -> String?
        def mitigation_strategy?: () -> bool
        def mitigation_strategy_valid?: () -> bool
      end
    end
  end
end
