module SBOM
  module CycloneDX
    module Record
      class ServiceData < Base
        def initialize: (flow: String, classification: String, ?name: String?, ?description: String?, ?governance: DataGovernance?, source: uri | String, destination: uri | String) -> void

        def flow: () -> String
        def flow=: (String) -> String
        def flow?: () -> bool
        def flow_valid?: () -> bool

        def classification: () -> String
        def classification=: (String) -> String
        def classification?: () -> bool
        def classification_valid?: () -> bool

        def name: () -> String?
        def name=: (String?) -> String?
        def name?: () -> bool
        def name_valid?: () -> bool

        def description: () -> String?
        def description=: (String?) -> String?
        def description?: () -> bool
        def description_valid?: () -> bool

        def governance: () -> DataGovernance?
        def governance=: (DataGovernance?) -> DataGovernance?
        def governance?: () -> bool
        def governance_valid?: () -> bool

        def source: () -> (uri | String)
        def source=: (uri | String) -> (uri | String)
        def source?: () -> bool
        def source_valid?: () -> bool

        def destination: () -> (uri | String)
        def destination=: (uri | String) -> (uri | String)
        def destination?: () -> bool
        def destination_valid?: () -> bool
      end
    end
  end
end
