module SBOM
  module CycloneDX
    module Record
      class Tools < Base
        def initialize: (?components: Array[Component]?, ?services: Array[Service]?) -> void

        def components: () -> Array[Component]?
        def components=: (Array[Component]?) -> Array[Component]?
        def components?: () -> bool
        def components_valid?: () -> bool

        def services: () -> Array[Service]?
        def services=: (Array[Service]?) -> Array[Service]?
        def services?: () -> bool
        def services_valid?: () -> bool
      end
    end
  end
end
