type fieldValue = String |
                  Integer |
                  Float |
                  bool |
                  DateTime |
                  URI |
                  EmailAddress::Address |
                  Array[fieldValue] |
                  SBOM::CycloneDX::SchemaObject::ClassMethods |
                  nil

type uriString = String | URI::HTTP
type emailString = String | EmailAddress::Address

type jsonObject = Float | Integer | String | bool | Array[jsonObject] | Hash[String, jsonObject] | nil

module URI
  def self.parse: (String) -> URI

  class HTTP
  end
end
