module SBOM
  module CycloneDX
    VERSION: String

    class Error < StandardError
    end

    module Boolean
    end

    module Union
      def self.build: (*Validator::fieldType) -> ConcreteUnion

      module ConcreteUnion
        def types: () -> Array[Validator::fieldType]
        def valid?: (untyped, **untyped) -> bool
      end
    end

    # TODO: Remove these when types are implemented
    class Composition < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Condition < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Copyright < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class CryptoProperty < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class DataGovernanceResponsibleParty < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class DataGovernance < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Declarations < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Definitions < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Dependency < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Diff < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class EnergyConsumption < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class EnergyMeasure < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class EnergyProvider < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class EnvironmentalConsideration < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Event < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class ExternalReference < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class FairnessAssessment < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Formula < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Graphic < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class GraphicsCollection < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class HashData < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class IdentifiableAction < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class InputOutputMLParameter < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Input < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Issue < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class License < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Metadata < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class ModelCard < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Note < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class OrganizationalContact < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class OrganizationalEntity < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Output < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Parameter < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Patch < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class PerformanceMetric < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class PostalAddress < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Property < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Rating < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class ReleaseNote < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class ResourceReferenceChoice < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Risk < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Root < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class SecuredBy < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class ServiceData < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Service < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Standard < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Step < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class SWID < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Task < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Tools < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Trigger < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Version < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Volume < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class VulnerabilitySource < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Vulnerability < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Workflow < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
    class Workspace < ::Struct[untyped]
      include SchemaObject
      extend SchemaObject::ClassMethods
    end
  end
end
