module SBOM
  module CycloneDX
    module Field
      class EmailAddress < Base[emailAddress]
        def initialize: (
          name: Symbol,
          ?required: bool,
          ?const: emailAddress | NotSet,
          ?default: fieldDefault[emailAddress] | NotSet,
          ?json_name: ::String?
        ) -> void
      end
    end
  end
end
