module SBOM
  module CycloneDX
    module Field
      class Union [T < fieldValue] < Base[T]
        def initialize: (
          name: Symbol,
          of: ::Array[Validator::UnionValidator::unionableValidatorParams],
          ?required: bool,
          ?const: T? | NotSet,
          ?default: fieldDefault[T] | NotSet,
          ?json_name: ::String?
        ) -> void
      end
    end
  end
end
