module SBOM
  module CycloneDX
    module Field
      class URI < Base[uri]
        def initialize: (
          name: Symbol,
          ?required: bool,
          ?const: uri | NotSet,
          ?default: fieldDefault[uri] | NotSet,
          ?json_name: ::String?
        ) -> void
      end
    end
  end
end
